### ISSUE TITLE
Read logs from container

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#111]
Now that logs are set up in #42 we need to actually obtain them from the deployed container.

**Comment by rwblickhan** [comment]
Having researched this, the best option appears to be to use the [logging drivers](https://docs.docker.com/config/containers/logging/configure/) built in to Docker. In particular, these can be [set up in `docker-compose.yml`](https://docs.docker.com/compose/compose-file/#logging). The most promising of these is probably the [fluentd logging driver](https://docs.docker.com/config/containers/logging/fluentd/), or the [AWS CloudWatch](https://docs.docker.com/config/containers/logging/awslogs/) one if we're definitely going to be using AWS.

**Comment by cheukyin699** [comment]
If we use AWS CloudWatch, we need to configure a few things:

1. [IAM policy for the EC2 instance][ec2]
2. Install CloudWatch agent `sudo yum install -y awslogs`
3. [Configure CloudWatch agent][agent-config]

I'm not sure how everything works yet, but I know for a fact that if we set it up to listen to docker logs, our logs would also show up.

[ec2]: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_cloudwatch_logs.html#cwl_iam_policy
[agent-config]: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_cloudwatch_logs.html#configure_cwl_agent

**Comment by cheukyin699** [comment]
Also, right now you cannot run the server properly because the core requires the facade and slack bot on initialization, which is not there. I know how to initialize the former, but not the latter. I have it currently changed to:

```python
from db.facade import DBFacade
from db.dynamodb import DynamoDB
from bot.bot import Bot
import os
import logging

app = Flask(__name__)
core = Core(DBFacade(DynamoDB()), Bot(None))
```

Which is not sustainable because of the `None`.

**Comment by rwblickhan** [comment]
This should probably be lower priority, because these logs _are_ captured by `docker logs`, albeit this requires SSHing into the server and is rather inconvenient.

**Comment by cheukyin699** [comment]
There is a library that handles most of the heavy lifting for us: https://github.com/kislyuk/watchtower

Worth checking out.
