### ISSUE TITLE
Research scheduled events

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#117]
To implement features like #36 we’ll need a way to schedule events to fire at particular times. Since we’re running everything in a single process, we can’t use cron or similar.

**Comment by rwblickhan** [comment]
One possibility to consider is [`sched`](https://docs.python.org/3/library/sched.htm), provided by the standard library, though I’m not sure that it actually meets our requirements.

**Comment by cheukyin699** [comment]
Another such option would be [crontab][ctab].

[ctab]: https://github.com/robdmc/crontabs

**Comment by cheukyin699** [comment]
We would need to be able to:

- add a regularly scheduled event

We would need a basic model for a simple event that the scheduler can read. Later we can build off of it. But for now it should be good.

**Comment by cheukyin699** [comment]
Another thing we can look at is [APScheduler](https://github.com/agronholm/apscheduler).
