### ISSUE TITLE
IAM user unable to read logs on Amazon Cloudwatch

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#120]
![image](https://user-images.githubusercontent.com/6824907/48972379-c2cfa880-efdd-11e8-9e96-b0bc34a23f89.png)

Cannot view logs due to permission issues (though I don't think there are any yet).

**Comment by rwblickhan** [comment]
Fixed - everyone on the team should have full access to CloudWatch Logs now.
