### ISSUE TITLE
@rocket checks for the String, not Rocket SlackID

### ISSUE THREAD

**Issue by jacqueschen1** [ubclaunchpad/rocket2#141]
Currently, the core checks for the string "@rocket" instead of checking for the Rocket SlackID, a converter should be implemented that identifies Rocket's SlackID and changes it to @rocket

**Comment by rwblickhan** [comment]
This is probably obviated by #147 - I don't think the slash commands need `@rocket` at all. @cheukyin699 can you confirm?

**Comment by cheukyin699** [comment]
Yes. slash commands don't need `@rocket` at all.

**Comment by rwblickhan** [comment]
Okay, closing this then.
