### ISSUE TITLE
Implement team commands

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#142]
Here is the list of stubs to finish off:

- [x] team list
- [x] team view
- [x] team delete
- [x] team create
- [x] team add
- [x] team remove
- [x] team edit
- [x] team lead

Fill this in when you finish, and when they all are finished, close this.

**Comment by rwblickhan** [comment]
It might make sense to split this into smaller subtasks - we can decide this weekend.
