### ISSUE TITLE
Update local development docs to include containerization

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#145]
The local development tutorial is written assuming you're running the server directly. We should update it to explain how to run it via Docker.

Also, we might want to rename those docs... Currently they're titled "Linking Your Dev Server to Slack", which is correct, but it might be more obvious to call them "Local Development Tutorial" or something similar.

**Comment by rwblickhan** [comment]
Assigning @cheukyin699 and @michaelenglo; I think this task is relevant to what both of you are working on.

**Comment by cheukyin699** [comment]
Will be done as soon as we figure out a reliable way to run Docker or something.
