### ISSUE TITLE
Add check for Github ID after editing Github username

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#172]
In `UserCommand`, users can edit their Github username. When this happens, we need to do two things:
* Check for what ID is associated with their Github username.
* Store both the new Github username and the associated ID in the database (if either of those have changed).

This will require two changes:
* Update `UserCommand` to do the above behaviour.
* Add a method to the Github interface created in #161 to query for a Github ID given a Github username.

**Comment by ravenCondol** [comment]
Finding users given their IDs was not supported by pygithub. Superseded by #176
