### ISSUE TITLE
Github API with slack commands

### ISSUE THREAD

**Issue by omar2535** [ubclaunchpad/rocket2#186]
We want to implement new slack commands under /rocket team project {command}

**Comment by CoffeeTableEspresso** [comment]
Where can I find the code for the other slack commands?

**Comment by rwblickhan** [comment]
All commands should be in the `command/commands` directory.

**Comment by rwblickhan** [comment]
In particular, you're probably looking for `team.py`.

**Comment by rwblickhan** [comment]
Blocked by #189.

**Comment by cheukyin699** [comment]
Closing because stale.
