### ISSUE TITLE
Add meeting reminders on Fridays.

### ISSUE THREAD

**Issue by jackattackyang** [ubclaunchpad/rocket2#190]
With the influx of new members it would be great if on Fridays Rocket2 can send a reminder of the meeting time and location just so there's no confusion.
Thanks!

**Comment by bobheadxi** [comment]
Actually, kind of building on a generalization of this idea - what about a way for Rocket to directly message members with announcements? For example, meeting times and locations

**Comment by bobheadxi** [comment]
Clarification for self - I believe this refers to the weekly club meetings, which we don't have this semester

**Comment by bobheadxi** [comment]
I'm actually going to close this one out - scheduled reminders are probably better done via Google Calendar or Slack's built-in reminders feature.
