### ISSUE TITLE
Incomplete help text in user commands

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#192]
When you use the command

```
/rocket user edit help
```

you see that it helpfully displays only a subset of what is actually available to edit. One of the things that is blatantly missing (but extremely important) is the GitHub username. Please fix the documentation. If you find anything else that is blatantly obvious, please also let us know.

It may be a good idea to see how the `docs/UserCommands.md` says, just to get a feel for everything.

**Comment by rwblickhan** [comment]
I believe the old version of Rocket (and @bfbachmann might be able to talk about this) actually had some way to validate that the help for each command actually included all the implemented commands. We will probably want to do something similar.

**Comment by cheukyin699** [comment]
No longer relevant. Closing.
