### ISSUE TITLE
Implement help command

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#193]
When we type `/rocket help`, we want to display a help menu, somewhat similar to the original version of Rocket. This can probably be hardcoded into `handle_app_command()` in `Core`. In particular, each `Command` in `__commands` already has a help string available - the best implementation is probably to get the help string for each `Command`, concatenate them (with some formatting), then return it with a 200 status code.

**Comment by rwblickhan** [comment]
It would probably be a good idea to check all the documentation and update if necessary.

**Comment by bobheadxi** [comment]
I don't think you need to hardcode it - aren't you guys using `argparse`?

[`self.print_help`](https://docs.python.org/2/library/argparse.html#printing-help)

**Comment by rwblickhan** [comment]
... well then.

**Comment by cheukyin699** [comment]
May need a bit of formatting, but yeah that looks like it'll do the trick; I wonder why we never did this‽‽‽

**Comment by bobheadxi** [comment]
[Formatting? 😉 ](https://docs.python.org/3/library/argparse.html#formatter-class)

**Comment by rwblickhan** [comment]
I should probably note that this is for a _different_ help menu than what we’re using argparse for. We split the argument and pass it to a `Command` class, which internally uses argparse. However, the global help command is supposed to be listing all possible commands, which we will have to “hardcode.” 

That being said, that function should be useful for individual commands.

**Comment by rwblickhan** [comment]
In particular, @ravenCondol, keep implementing it as described in the issue description - we’ll make another issue to fix the individual command help menus.

**Comment by rwblickhan** [comment]
Created #202 to cover switching to `argparse`'s built-in help delivery. Also I noticed that `format_usage` and `format_help` return a string directly, instead of writing to a file - much more convenient than `print_usage` and `print_help`.
