### ISSUE TITLE
Kudos system

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#201]
This definitely requires a bit more thought:

* we need incentive to give kudos
* we need a good way to show kudos (leaderboards?)

Bonus points for:

* automatic kudos per PR or Issue created
    * more bonus point for a smart scaling system that reduces kudos given for tech leads and for consecutive PRs and issues
* NFC tags + mobile app, so people can tap someone with their phone and give them Rocket Kudos™️ 

- [x] Make command docs
- [x] Add into User Models
- [x] Add command

**Comment by rwblickhan** [comment]
What do you mean by incentive? Isn’t that the presidents job? 😛

I think as an MVP for this feature we just need to add a kudos/karma field to a user and a command to add/remove kudos/karma (probably with some limits?).

**Comment by bobheadxi** [comment]
By incentive I was thinking something automated, like... adding a `kudos-giver` flair, or a bonus multiplier on kudos you receive 🤔 

I don't think we should allow kudos removal - positive reinforcement!

**Comment by rwblickhan** [comment]
Yeah I agree - the only reason my karmabot included karma removal was because it was a pretty direct clone of an existing bot that I used on... Hipchat....

Sure, we can have an automated feature, but that still sounds like something for our daring PM Robert to decide 😛

**Comment by bobheadxi** [comment]
paging @bfbachmann @frostyshadows for thoughts 😋

**Comment by bfbachmann** [comment]
Yea this sounds okay. The NFC tags thing sounds a bit weird, though.

**Comment by cheukyin699** [comment]
Here's how other people do karma:
![image](https://user-images.githubusercontent.com/6824907/53290688-93574600-375c-11e9-83e5-0f724152ba24.png)

Just wanted to put this somewhere.

**Comment by cheukyin699** [comment]
Karma done
