### ISSUE TITLE
Add admin-level command to make other users admin

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#207]
Right now I believe we have to edit a user directly in the database to make them an admin. Clearly this won't be sustainable. We should add an admin-level subcommand to `/rocket user` that changes their permission level - possibly only upwards, to prevent infighting.

**Comment by cheukyin699** [comment]
What would be preventing a user to invoke the command directly and gain admin privileges?

**Comment by rwblickhan** [comment]
It would be admin level - that is, you would need to be an admin already to invoke it.

**Comment by cheukyin699** [comment]
So we only need 1 user to be an admin to get everyone else on the ball?

**Comment by rwblickhan** [comment]
Yes, that’s my idea here - it would enable us to smoothly introduce new tech leads (and possibly remove them as well) as people join/leave.

**Comment by bobheadxi** [comment]
Is there a plan for another permission level, or is admin and normal member the only "tiers"? I think it might be nice to have a tier below admin and above normal member for leads that can't do things like delete teams or remove users, especially if LP / whatever org using rocket has a lot of team leads

**Comment by rwblickhan** [comment]
We discussed this in #39, @bobheadxi 😛

**Comment by bobheadxi** [comment]
Damn I’m getting old :(

**Comment by rwblickhan** [comment]
Old Man Robert 😛

In fairness we haven’t really used tech lead level... would definitely accept comments on what that might bee used for.

**Comment by bobheadxi** [comment]
I think just to make sure only admin admins can completely delete people, etc - ie lock "destructive" actions to a tier above the "lead level"

**Comment by bobheadxi** [comment]
Also I feel an admin should be able to edit other people - ie, if someone writes something bad and it shows up on the website, etc.

**Comment by rwblickhan** [comment]
Admins should be able to edit other profiles already.

So essentially tech leads should have everything we're reserving for admins right now, _except_ destructive commands?

**Comment by bobheadxi** [comment]
yeah that sounds fine for now 👍
