### ISSUE TITLE
pycodestyle defaults to 79 character lines instead of 80

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#214]
By default, `pycodestyle` checks for lines that exceed 79 characters in length, which I think is not our intention (more than 80 characters).

Some more information [here][defaults]. The flag `--max-line-length=n` should help a bit.

[defaults]: https://pycodestyle.readthedocs.io/en/latest/intro.html#example-usage-and-output

**Comment by cheukyin699** [comment]
Irrelevant, just like Logan Paul.

**Comment by rwblickhan** [comment]
Some editors will display a line break explicitly, so in some cases this would be an "80th character" that pycodestyle wouldn't detect - this is likely why pycodestyle defaults to 79, not 80, characters.
