### ISSUE TITLE
Set up slack/md format module

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#218]
See https://github.com/ubclaunchpad/rocket2/pull/216#discussion_r255385100

In summary, something like:

```python
def code(str):
    return "`{}`".format(str)

def code_block(str):
    return "```\n{}\n```".format(str)

def quote(str):
    return "> {}\n".format(str)

def emph(str):
    return "*{}*".format(str)
```

used like:

```python
return "This is your token: {}".format(slackfmt.code_block(token))
```

> i actually feel this is a pretty high priority, since the longer you wait the more you'll have to replace and the less likely anyone will want to do it 😋

**Comment by rwblickhan** [comment]
Since other Launch Pad Python projects might need this, we should consider putting this in another repo and packaging for PyPI.

**Comment by michaelenglo** [comment]
What happens when someone wants to have a message like `this \n is not meant to be a newline.`? Should we support this early on?
