### ISSUE TITLE
Organization PR stats, prize draws

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#22]
PR stats per person:
- number of reviews
- number of PRs
- turnaround time?
- example: https://pullreminders.com/installs/12406312/leaderboard?dates=30d&view=reviews

Prize draws:
- weighted by a metric (# of PRs, # of reviews, etc.)
- ability to exclude team leads
- send winner's name to `#general` on defined intervals, with lots of emoji

**Comment by cheukyin699** [comment]
Closing because stale and not much followup.
