### ISSUE TITLE
Add type annotations to data model

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#23]
Once our data model starts stabilizing a bit more, we should add type annotations from the [`typing`](https://docs.python.org/3/library/typing.html) standard library module and add type checking to our Travis builds.

**Comment by cheukyin699** [comment]
I can help with this, once the data model starts stabilizing.

**Comment by rwblickhan** [comment]
Probably best to finish #221 before this, so we have less code to annotate.

**Comment by cheukyin699** [comment]
As soon as #231 is merged, I will start this.
