### ISSUE TITLE
Project equality test does not pass because time.time goes too slowly

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#240]
**Describe the bug**

The test `test_project_equalities` does not pass for some computers because their implementation of `time.time()` is too slow.

**To Reproduce**

1. Run the test `tests/model/project_test.py`; it may or may not occur depending on your system (the only 2 reports of this are from Windows machines).

**Expected behavior**

The tests are supposed to pass.

**Screenshots**

![image](https://user-images.githubusercontent.com/6824907/53302200-fe625480-3810-11e9-91f7-650c7ab42207.png)

**Additional context**

Windows. Windows. Windows. Windows.

**Comment by cheukyin699** [comment]
One sure fire way to get rid of the bug (I think) is to use `datetime.datetime.utcnow()` instead of `time.time()`.

**Comment by ravenCondol** [comment]
how about using UUID instead of time? it apprears (https://stackoverflow.com/questions/34344836/will-hashtime-time-always-be-unique) hashing with time is notgood

**Comment by cheukyin699** [comment]
Sounds like a good idea to me. Let's use UUID instead of time
