### ISSUE TITLE
Use formatted strings everywhere

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [ubclaunchpad/rocket2#246]
Python 3.6 onwards supports something called `f-strings`. Instead of `"x is " + str(x)`, you can write `f"x is {x}"`. f-strings use the same formatting syntax as the existing `format`, but are much cleaner.

I suggest using f-strings throughout our codebase, and in the future for new code.

**Comment by rwblickhan** [comment]
https://cito.github.io/blog/f-strings/

According to this blog, Pycharm is able to automatically convert calls to `format()` to f-strings; may be useful.
