### ISSUE TITLE
Fix webhook url and make configurable

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#260]
**Describe the bug**
It looks like Github Apps wants to deliver _all_ webhook events to a single url. Right now we receive team events through `/webhook/team` and organization events through `/webhook/organization`. Refactor this so that there is a single API endpoint that all webhook events are delivered to, and figure out which webhook handler to call based on the event payload.

Also, go ahead and make this endpoint configurable, by adding a field to the `github` section of `config.toml`.

**Comment by rmcreyes** [comment]
Also update the local development guide to describe how to create and add a `webhook_secret` to the Github App.
