### ISSUE TITLE
Create a nicer status page

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#278]
**Please give a one-sentence summary of the feature you would like to see.**

We have a status page but it's just a simple emoji and could be nicer.

**Please give as many details as possible about the requirements for the feature.**

I think the best way to implement this would be a simple React (or whatever?) frontend served on `/` (and _only_ on `/`) that tried to contact a new `/status` endpoint and displayed a success message as appropriate.

**Comment by cheukyin699** [comment]
So this will be 2 things: a new `/status` endpoint that returns some data, and a frontend on `/` that parses the data from `/status`?

**Comment by rwblickhan** [comment]
Yes, I think that would make sense. That way we could still serve the static frontend via Nginx, which could then display a more useful error message when Rocket 2 is down.

**Comment by cheukyin699** [comment]
See #350, which encompasses this.

**Comment by bobheadxi** [comment]
Reopening, since I think #350 should focus on a docs landing page (highlighting features, capabilities, etc), and this is more of a "status of Rocket" type deal

**Comment by bobheadxi** [comment]
Closing in favour of more features and details in https://github.com/ubclaunchpad/rocket2/issues/565
