### ISSUE TITLE
Config file still includes github section

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#279]
**Please give a one-sentence summary of the cleanup you would like done.**

Remove github section from `config.toml`.

**Please give as many details as possible about the cleanup or refactoring.**

The config file `config.toml` still has the `[github]` section, but we have already moved on, and the program will now throw an error if file `credentials/github.toml` is not present. The docs must also be updated to reflect this (must specify the relevant fields).

**Comment by rwblickhan** [comment]
This ticket is incorrect - the Github section in `config.toml` is required to configure `app_id` and `organization` (unless I missed something and these aren't being use anymore). We _also_ need the `credentials/github.toml` to contain the webhook secret we use to ensure webhook requests are actually from Github. This is similar to how we have both `aws`/`slack` sections and `aws.toml`/`slack.toml`.

That being said, we should definitely consider opening up a ticket to refactor all of this configuration and credentials stuff - it's kind of a mess.

Closing.
