### ISSUE TITLE
Add SlackEvent to data model

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#28]
Add a SlackEvent class to `model/` to represent a [Slack event parsed from JSON](https://api.slack.com/events-api#receiving_events). In particular, it should have (de)serialization functions (to convert to and from JSON). It may also be helpful to have "sub data types;" for instance an enum for the [possible event types](https://api.slack.com/events-api#event_types) (or at least the ones relevant to Rocket 2.0's MVP).

**Comment by rmcreyes** [comment]
It seems as though each Slack event's JSON string has an inner JSON object as a property, and this object has a different structure depending on the kind of event.

This is a full example of the structure of a Slack  `reaction_added` event. Take notice of the `event` object: 
![image](https://user-images.githubusercontent.com/31678646/46719663-5d894900-cc23-11e8-83e1-e4fad4c79a73.png)

The event documentation provides detail of the structure of other events, where in most cases only the `event` attribute's structure is shown, and in others the full structure is shown, like in this `link_shared` event:

![image](https://user-images.githubusercontent.com/31678646/46720067-51ea5200-cc24-11e8-9d7a-7e40edd420d5.png)

In some cases, the event does not even have an `event` attribute at all, like in this `app_rate_limited` event:
![image](https://user-images.githubusercontent.com/31678646/46720146-8958fe80-cc24-11e8-9f6d-0afecb59fe67.png)

The simplest way to handle this in my opinion is to serialize the outer attributes, as well as the `type` attribute of the inner `event` object to identify the kind of event at least, and leave the inner `event` object as a String attribute of the SlackEvent class being built, but I am open to suggestions as to how to handle this.

**Comment by rwblickhan** [comment]
I believe we've decided not to go down this route, at least for the time being; closing.
