### ISSUE TITLE
Add script to set up credentials

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#285]
**Please give a one-sentence summary of the feature you would like to see.**

Add a script that copies credentials to the correct place.

**Please give as many details as possible about the requirements for the feature.**

We have a lot of required credentials. It would be nice to have a script that validates that all required credentials are in place, or allows you to one-by-one copy them into the credentials directory.

**Comment by cheukyin699** [comment]
Also remember to add docs to both LocalDevelopmentGuide.md and Scripts.md
