### ISSUE TITLE
Implement project commands

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#294]
Ref #177 

I see that all necessary models and documentation are in place. Which leaves us with the most important and functional part: the actual commands themselves!

Please implement project commands as per the documentation. If there is anything unclear about them, please ask in the comments.

**Comment by cheukyin699** [comment]
Projects require a github team id, meaning that we need to have some way to cross reference that. We propose to add the slack channel id to the team model, associating the channel with the team model directly, so that we can use the channel id to look up the team id.

**Comment by rmcreyes** [comment]
Reminder that we actually agreed to have the github team name as a parameter to the `create` subcommand, as querying for a team with that team name will provide the appropriate github team id. This would also require asserting that whoever is creating the project needs to be a team lead of the team to assign the project to. The docs will need to be changed for this.
