### ISSUE TITLE
Security issue with slash commands endpoints

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#295]
Currently, we do not authenticate any of our slash command requests on the server-side. This means that any yahoo could go in (after acquiring a team-lead/admin's slack id), and just pretend to be a user and screw up all of our data and database.

This is extremely dangerous because, well, it can potentially screw up everything (good thing we have yet to use this in actual production). This is an issue of request validation, which must be fixed as soon as possible.

To the person assigned to this issue, [slack has a way of signing their requests][way]. They use the signing secret and combine it with the request body to create a unique hash. You only need to verify that it is indeed correct on the server before you process the request.

[way]: https://api.slack.com/docs/verifying-requests-from-slack

**Comment by rmcreyes** [comment]
It seems as though Slack also recommends using signed requests for the Events API, ie. we also need to do this for the Slack events we subscribed to, which for now are `app_mention` and `team_join`.

**Comment by cheukyin699** [comment]
I suggest that we put verification logic into the `utils/` directory, since people reading the code in `server` probably don't want to see how the things are verified. Also try to abstract out the verification stuffs for Github webhooks to the `server.py` level.
