### ISSUE TITLE
Refactor team event handler

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/rocket2#300]
**Please give a one-sentence summary of the cleanup you would like done.**
`handle_team_event()` is the only webhook handler method that is not broken down to helper methods. Fix this.

**Please give as many details as possible about the cleanup or refactoring.**

**Please list any additional context; in particular, list what areas of the code base this would affect.**

**Comment by cheukyin699** [comment]
**300th issue HYPE**
