### ISSUE TITLE
Add documentation on how to contribute

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#324]
It seems like we are lacking documentation on how developers can contribute to this project. Please add this.

**Comment by rwblickhan** [comment]
We actually do have a [CONTRIBUTING.md](https://github.com/ubclaunchpad/rocket2/blob/master/CONTRIBUTING.md) but it could use some work.

**Comment by cheukyin699** [comment]
Oof. This is over 7 months old

**Comment by rwblickhan** [comment]
Like I said... it could use some work... 😛 

That being said, it's definitely the right place to put it, since that's what shows up in the sidebar of a pull request.
