### ISSUE TITLE
Repeated call of team_deleted() GitHub webhook

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/rocket2#326]
**Describe the bug**
When manually testing GitHub webhooks, deleting a team appears to attempt to delete a team from Rocket's database, which it does successfully, then attempting to delete the same team again, which it does not do successfully.

**To Reproduce**
1. Configure test GitHub organization to send webhooks to Rocket
2. Delete a team from the test organization
3. See the error in the logs

**Expected behavior**
The second attempt to delete the team should not happen.

**Screenshots**
[multiple_db_call.log](https://github.com/ubclaunchpad/rocket2/files/3389192/multiple_db_call.log)

**Additional context**

**Comment by cheukyin699** [comment]
Not really a priority, but we should confirm whether this happens to other webhooks or not (Robin only tested on team webhooks, not the other webhooks). I personally tested on member_invited (I think that's what it's called), that triggers whenever we invite someone from the organization. That one only fired once.

A weird issue, probably not our highest priority, but still something to look into.

**Comment by bobheadxi** [comment]
I've noticed this in the past, where GitHub dispatches similar webhooks of different types for the same event - it might be that rocket is catching this event in different forms

**Comment by cheukyin699** [comment]
The repeated calls to team deletion don't seem to happen any more. Closing.
