### ISSUE TITLE
User's GitHub ID is not set automatically when username is set

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/rocket2#327]
**Describe the bug**
Most operations involving GitHub require a user's GitHub ID, which is never set (see `edit_helper()`. This prevents operations like the `mem_added()` from working properly.

**Expected behavior**
GitHub ID should be set at the same time the GitHub username is set.

**Comment by cheukyin699** [comment]
One solution is to edit the `interface/github.py` add* functions to return the user id, and then just use the user id there. A quick and easy fix.
