### ISSUE TITLE
Travis build errors randomly

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#334]
**Describe the bug**
The travis builds will error randomly, mostly because of some key/hash mismatch.

**To Reproduce**
1. Push a branch
2. Wait for it to error (by restarting it when it doesn't)

**Expected behavior**
It should be reliable, and not error, but rather fail.

**Additional context**
It seems like everyone is finding this to be a problem, and it has been this way from the start of this year.

https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728/13

**Comment by cheukyin699** [comment]
Maybe we could do something like a while loop that runs when `sudo apt-get update` fails. May bloat the `.travis.yml` file a bit though.

**Comment by rmcreyes** [comment]
Using GitHub Actions now
