### ISSUE TITLE
Let everyone create a team

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#336]
**Please give a one-sentence summary of the feature you would like to see.**

Anyone should be able to create a team.

**Please give as many details as possible about the requirements for the feature.**

When a member creates a team, they are immediately the team lead of the team. If an admin creates a team, they don't have to be the team lead.

**Please list any additional context.**

I want to abolish the global team lead permission. I have a dream. That all members are created equal (except for the admins). It should just be a local permission.

**Comment by bobheadxi** [comment]
An important thing to consider here is adaptability - it is easy to give permission for someone to create a team, and not every organization using Rocket will *want* everyone to be able to create a team, or to create a repo, etc.

Having an additional "team lead" permission could be very useful to prevent potential abuse
