### ISSUE TITLE
Remove team display name in model

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#337]
**Please give a one-sentence summary of the feature you would like to see.**

Remove it.

**Please give as many details as possible about the requirements for the feature.**

Github does not use this. We don't need to use this as well. Github is the source of truth.

**Comment by rwblickhan** [comment]
So to be clear, you’re proposing to use the canonical Github team name for all purposes, including display? What if we want to display teams on the website with data pulled from Rocket?

**Comment by cheukyin699** [comment]
We use the github team name instead. It will change automatically when (if) we change it on github.

**Comment by rwblickhan** [comment]
Does the Github team name have any restrictions? Or can it literally be anything? (e.g. I know our team is called `brussel-sprouts` but I'm not sure if that's due to Github restrictions or old Rocket restrictions)

**Comment by cheukyin699** [comment]
The name can be anything. The slug is autogenerated. It looks like we are saving the name and not the slug. Which should suffice as a team name (because it ain't a slug).

**Comment by rmcreyes** [comment]
Decided that a team display name is still relevant to keep around, as having a website displaying just the github team names might be kinda ugly :)
