### ISSUE TITLE
Feature random channels

### ISSUE THREAD

**Issue by tiffanywu0313** [ubclaunchpad/rocket2#36]
Feature request: every week, feature a random public channel to help with channel discovery (for example, `#rock-it-beats` or `#interview-prep`)

**Comment by rwblickhan** [comment]
See #117 for research into scheduling events on Rocket.

**Comment by cheukyin699** [comment]
We here in the rocket2 team are hard at work and are working towards a solution. Here's a screenshot:

![image](https://user-images.githubusercontent.com/6824907/58757445-97180880-84c1-11e9-8910-7c6fb3bac8b6.png)
