### ISSUE TITLE
/rocket team create doesn't add yourself as a team lead if you didn't specify it

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#376]
**Describe the bug**
`/rocket team create` doesn't add yourself as a team lead if you didn't specify explicitly that you are a team lead.

**To Reproduce**
1. `/rocket team create brussel-sprouts`

**Expected behavior**
To be added as a team lead.

**Comment by rmcreyes** [comment]
This sighting seems to have been caused by the OAuth bug discovered the other day, and this functionality seems to be working.
