### ISSUE TITLE
Double-dash not recognized by parser in iOS (Unicode)

### ISSUE THREAD

**Issue by phillytan** [ubclaunchpad/rocket2#384]
**Describe the bug**
iOS would merge the double-dash into a single longer-dash as part of its keyboard settings and this would lead to rocket not recognizing double-dashes in the commands.

**To Reproduce**
run command '/rocket user edit --name "name"' in an iOS Device

**Expected behavior**
For rocket to understand iOS' long-dash as a double-dash.

**Comment by cheukyin699** [comment]
Have a look at https://support.apple.com/kb/PH26552?viewlocale=en_US&locale=en_US

You can copy and paste the dashes there.

**Comment by phillytan** [comment]
Thanks Cheuk! I'll take a look into this.
