### ISSUE TITLE
tiered permission model

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#39]
The current Rocket only has admins and everyone else - it's probably more flexible to have an additional `lead` position that has permissions like team and repo creation. Something like:

- admin: create, delete, read
- lead: create, read
- everyone else: read

**Comment by rwblickhan** [comment]
This is part of our roadmap (in fact if you look at [`permissions.py`](https://github.com/ubclaunchpad/rocket2.0/blob/master/model/permissions.py) you'll see that `TEAM_LEAD` is one of the three possible permissions levels) though I'm noticing a bit of confusion about that - I didn't explicitly write it down in our docs, so I may update those at some point (and close this when I do).

**Comment by rwblickhan** [comment]
This is already part of our data model and included more specifically in other tickets; closing.
