### ISSUE TITLE
Create cute logo/mascot

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#390]
![image](https://user-images.githubusercontent.com/23356519/67175894-a9191b80-f37c-11e9-991a-49354f800e76.png)

not the most flattering face 🙃 

see: [inertia mascot](https://github.com/ubclaunchpad/inertia/blob/master/README.md)

**Comment by rwblickhan** [comment]
pinging @frostyshadows because she still owes us a durian mascot 😉
