### ISSUE TITLE
Give names of members in /rocket team view

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/rocket2#396]
**Please give a one-sentence summary of the feature you would like to see.**
Instead of the Slack ID of each member, list the actual names of the people in each team detailed by `/rocket team view`

**Please list any additional context.**

This was requested as a convenience from Yichen.

**Comment by cheukyin699** [comment]
Probably a simple way to do this would be to use a query:

```python
members = facade.query_or([('github_id', '12344567'), ('github_id', '43217546')])
names = list(map(lambda m: m.github_username, members))
```

But the way we are getting the attachments means we need to add a new argument to the `get_attachment()` function, which, though less than ideal, should be a good way to go (not much of a reason semantically why a model method should take a database facade as parameter).

The other even-less-than-ideal way, which IMO would take even more work, not to mention slightly more latency, would be to rework how we take in members to begin with. We would still store the members and team leads by their ids, but every time we retrieve or query a team, we would do another lookup for all of the associated ids and get the users associated and attach them to the team model. This requires a complete overhaul of how the database and models interact, as well as a few fixes as to how we currently call the functions to begin with. On the bright side, we would get something similar to the foreign keys you would see in MySQL databases, which some people are familiar with.

@rmcreyes Thoughts?
