### ISSUE TITLE
question: github app permissions

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#415]
on [this page](https://rocket2.readthedocs.io/en/latest/docs/LocalDevelopmentGuide.html#set-up-github-app-and-organization):

> After doing this, you must go to the app’s “Permissions & Events” tab and set the following as read-only:
> * Organization hooks
> * Organization members

isn't write access needed for organization members, to modify teams? is there a particular reason why the recommendation here is for read-only? (I'm guessing might be related to dev, but could be oversight)

**Comment by cheukyin699** [comment]
Good question. Looks like an oversight.
