### ISSUE TITLE
Periodically poll website to check if it is down (ssl cert expiring prevention)

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#423]
**Please give a one-sentence summary of the feature you would like to see.**

When Rocket 2 goes down for any reason (say, when a `check()` fails), admins should be notified immediately.

**Please give as many details as possible about the requirements for the feature.**

Every day, Rocket 2 should poll the `check()` via HTTPS request and see if it succeeds with anything other than the intended 200 status code. If it fails, we notify all users that are admins.

**Please list any additional context.**

This is because of a recent issue we had with the SSL certificate **not** renewing like it was supposed to, and causing unintended downtime for about a few days, according to logs. It was noticed when a new member tried to use Rocket, and should have been caught a lot earlier than a few days for better user experience.

**Comment by rwblickhan** [comment]
Maybe you should consider Kubernetes 😛

**Comment by cheukyin699** [comment]
Hmmmmm....

**Comment by cheukyin699** [comment]
Added email notifications whenever the status check fails. Closing.
