### ISSUE TITLE
Look into forking pymarkdownlint

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/rocket2#43]
We're using [`mdl`](https://github.com/markdownlint/markdownlint) to lint Markdown (e.g. for documentation). This is rather inconvenient because it's written in Ruby but everything else is in Python 3. We tried using the (unmaintained) [`pymarkdownlint`](https://github.com/jorisroovers/pymarkdownlint) instead but it appears to be written in Python 2. We should investigate how easy it would be to convert this to Python 3 - if it would be relatively straightforward we should fork it and replace `mdl`.

**Comment by rwblickhan** [comment]
In particular if we fork it I think it would be a good idea to also convert it to `pipenv` for consistency and also have unit tests with Pytest (although that could also be a "down the road" type thing).

**Comment by rwblickhan** [comment]
Also we should consider installation - I believe `pipenv` uses PyPI by default and our fork wouldn't be available there (at least at first). If installing it from a Github repo would complicate things too much, it may not be worth switching.

**Comment by rwblickhan** [comment]
The Python [`2to3`](https://docs.python.org/2/library/2to3.html#to3-reference) may be helpful.

**Comment by cheukyin699** [comment]
Wow. That `2to3` tool is insanely helpful. I ran it and it just converted all the files from 2 to 3, without any other hassle. Currently working on the unit tests, and trying to get them to not error. I think it will take a bit to get a setup going.

**Comment by cheukyin699** [comment]
Work is here: https://github.com/cheukyin699/pymarkdownlint

**Comment by cheukyin699** [comment]
Python 3.7 is used for consistency with our project.

**Comment by cheukyin699** [comment]
> Also we should consider installation - I believe `pipenv` uses PyPI by default and our fork wouldn't be available there (at least at first). If installing it from a Github repo would complicate things too much, it may not be worth switching.

I looked into it, and installing from a Github repo isn't too far-fetched. Doable, at the very least, and fairly straightforward.

The conversion is done. Now will start trying to install it into `pipenv`.

**Comment by cheukyin699** [comment]
Installed nicely (cheukyin699/#43-get-pymdlint), but just found that pymarkdownlint only checks for 3 rules, whereas mdl checks for around 40 of them.

**Comment by cheukyin699** [comment]
It looks like the guy abstracted everything out, and there's only 1 file that defines the logic for all the rules, and similarly, each rule is basically one function.

I think that it's just a matter of converting them over from ruby. Basically, the thing has infrastructure to handle not just rules that concern a singular line, but also entire files as well.

The most difficult part would just be the logic and adding enough tests to cover everything.

**Comment by cheukyin699** [comment]
I've done the first 2 rules, and it sort of works, but is a bit hacky. What the original ruby gem does is it calls a Kramdown parser, parses through the object, adding additional metadata (line number, extra tags for easy find, etc.). The gist of it is that we'd need to write a parser (or at least a wrapper around an existing parser).

The first 2 rules I did I converted the markdown to html, and then from the html I put it into BeautifulSoup for easy traversing. It works, it's just that it probably doesn't scale all that well.

**Comment by cheukyin699** [comment]
The `markdown->html->object` method also doesn't work well for some of the rules that I'm looking at. For instance, there is a rule that enforces consistent header style:

```md
# header

## inconsistent ##

very inconsistent
=================
```

It relies heavily on the markdown coming in, and as such, we'll need a good/better parser. And I can't seem to find one.

**Comment by cheukyin699** [comment]
**OR** we can copy code from the existing one (the one that I use to turn markdown to html), and modify from there. But it also would take a while.

I think it is best not to touch things, since we are only using this for markdown linting.

Albeit, being a language/web team, this is sort of our forte.

**Comment by rwblickhan** [comment]
Closing for now - this definitely isn't in scope for Rocket 2.0, though we might want to consider this for another project or something.
