### ISSUE TITLE
Increase coverage for like the project

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#431]
**Please give a one-sentence summary of the cleanup you would like done.**
Increase the coverage for the project by omitting `tests` directory, omitting the things that aren't unit-tested, and adding more tests.

**Please give as many details as possible about the cleanup or refactoring.**
See above.

**Please list any additional context; in particular, list what areas of the code base this would affect.**
Like, most of it that has low coverage percentage.

**Comment by rwblickhan** [comment]
<img width="120" alt="Screen Shot 2020-02-01 at 2 50 26 PM" src="https://user-images.githubusercontent.com/13651149/73600247-320a2c00-4502-11ea-8b19-f14fb248e4c6.png">
😢
