### ISSUE TITLE
add all members to @ubclaunchpad/all 

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#459]
Old Rocket maintains a team, https://github.com/orgs/ubclaunchpad/teams/all, that makes it easy to "inner source" repositories (make repos visible to everyone within Launch Pad). [code](https://sourcegraph.com/github.com/ubclaunchpad/rocket@0eb8ecf425c01cd20672c549bde19c6bab0ec020/-/blob/plugins/core/set.go#L92)

We need Rocket2 to add everyone to this team as well

This is causing issues with folks access private repos - see https://ubclaunchpad.slack.com/archives/C061Q84SW/p1588451606003600

**Comment by cheukyin699** [comment]
We may want to add this functionality to `/rocket team refresh`. And also by default when a user provides their Github Username, we not only want to add them to the organization, but also want to add them to the `all` team.

- [ ] Add users to `all` team in `team refresh` command
- [ ] Add user to `all` team when they are added to the organization

After this, we can update Github with a simple `/rocket team refresh`, which hopefully won't break anything.

**Comment by bobheadxi** [comment]
Looks like it worked (mostly) - the org has 160 people, the `all` team has 153. I reckon that's close enough, can revisit if someone complains 🙃
