### ISSUE TITLE
General code cleanup and tidiness

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#465]
From the multiple hours of working on this codebase, I have noticed a few things that slowly start to creep up and accumulate over the years. These things build up into unspoken rules and weird parts such as:

- `__init__.py` files that are basically useless because they are almost empty
- classes and files and functions that have docstrings, but the docstrings state the obvious (e.g. "Initialize the dependencies of command APIs." for the __init__, with nothing else)
- duplicate comments that must be maintained (creating a multi-comment docstring dependency, which sounds more stupid now that I type this out)
- classes who's only purpose is to call the functions of another class (I'm looking at you, `db.facade.DBFacade` and `db.dynamodb.DynamoDB`)

There are other smaller issues, which are sometimes brought up. But this uncleanliness still stands. If this is to exceed the original `rocket`, it must go above and beyond to maintain good code styling and readability and consistency. We'd also want to avoid burdening the team in creating Rocket 3 in Rust.

**Comment by bobheadxi** [comment]
@cheukyin699 can we split these into more specific tickets and close this one?

**Comment by cheukyin699** [comment]
This was supposed to be an epic on zenhub, but then I stopped using it. So we probably close this one. Most of the things mentioned are already implemented.
