### ISSUE TITLE
many users seem to be getting their emails saved as `<me@email.com>` instead of `me@email.com`

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#502]
This might be related to the recent email unescape change? https://github.com/ubclaunchpad/rocket2/commit/6fb7aa645e1aeef6a09605f5fb00403b437ea297

Examples:

* https://ubclaunchpad.slack.com/archives/CK935RD3Q/p1601257501002700
* https://ubclaunchpad.slack.com/archives/CK93HTYQN/p1601177387006400?thread_ts=1601176672.004800&cid=CK93HTYQN

cc @cheukyin699

**Comment by cheukyin699** [comment]
More likely an issue of the phrasing in the documentation, where users substitute their emails and leave the angle brackets in. Documentation will need updating to reflect this.

**Comment by cheukyin699** [comment]
We will need to use another method to denote what you should be typing. Maybe single-/double-quotes.

**Comment by bobheadxi** [comment]
Ah, I didn't realize the brackets were there in documentation! Possible alternatives:

- `$EMAIL` (my fav)
- `[EMAIL]` (might not be that different from `<` though)
- `EMAIL` (commands are in lowercase, parameters in uppercase?)

**Comment by cheukyin699** [comment]
Okay. We'll use bash variables.
