### ISSUE TITLE
adding user to team without GitHub ID set throws obscure error

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#505]
@sandyklc was attempting to add design members and got an obscure error:

![image](https://user-images.githubusercontent.com/23356519/94404366-75a45b00-01a1-11eb-8091-fa56eb773cc0.png)

When I checked the relevant user, turns out that they just haven't set their usernames yet.

1. Error message should be more informative
2. Should we block users from being added to teams if they haven't set up GitHub yet? Could we set up GitHub teams after the fact similar to how drive permissions are sync'd?

**Comment by cheukyin699** [comment]
Assuming that everyone has a Github account, we'll need to gently push the user into adding their usernames and then worry about adding them to teams (if they haven't added their usernames they most likely aren't in the organization).

**Comment by cheukyin699** [comment]
Fixed in d6904b7
