### ISSUE TITLE
drive invites seem to be spammed for a few people

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#510]
I have not experienced this myself, and judging from the general lack of complaints this is generally not the case, but there is at least once case: https://ubclaunchpad.slack.com/archives/CK93HTYQN/p1601316108020500

* @jedyeo
* @ctong25

I'm surprised this is happening, because the code excludes existing shares:

https://sourcegraph.com/github.com/ubclaunchpad/rocket2/-/blob/interface/gcp.py#L38-49

We do log the entire permissions object, so we might be able to check the logs to see if there are any without an `emailAddress`. The email invite might contain the permission ID for easier search across the logs.

**Comment by bobheadxi** [comment]
I suspect this is caused by https://github.com/ubclaunchpad/rocket2/issues/497, and _might_ be partially resolved by #504 with 35e1209

**Comment by jedyeo** [comment]
![image](https://user-images.githubusercontent.com/33077039/94600922-860f1100-0247-11eb-8e3e-32fcddbf173a.png)

Rocket keeps spamming me with invites every couple of hours, so each time I accept the invitation, I gain permissions for the drive, but the next invite also seems to revoke those privileges.

This only seems to be happening for some users.

Timestamps of the invites:
Sept-27 3:12pm
Sept-27 6:31pm
Sept-27 8:36pm
Sept-28 12:56am
Sept-28 3:17am
Sept-28 8:52am
Sept-28 6:39pm

The invites seem to have stopped for now. Unfortunately I do not see anywhere on the email that contains a permission ID, so what I did was accept the invitation and was able to capture something that resembled a UID at the end of the browser link: `5f729053`. Sadly I do not know if this corresponds to anything.

@bobheadxi

**Comment by jedyeo** [comment]
OK, I just got another invite at 12:07pm today

**Comment by ctong25** [comment]
I also got it at that time too.
Best regards,
Claudia Tong
tong.claudia.25@gmail.com

**Comment by bobheadxi** [comment]
Thanks everyone!

@cheukyin699 do you mind checking if there's any permissions entries logs at some of these times where the permissions don't contain an `emailAddress`? (or DM me with how I can get myself set up with logs access)

**Comment by bobheadxi** [comment]
Changes from #504 did not seem to alleviate this issue. I'm almost certain it is caused by #497, but do not understand why it's not affecting some people (ie I don't receive duplicate invites)

**Comment by bobheadxi** [comment]
I'm hearing a lot more cases of this now, so I'm just going to go ahead and disable permissions deletion for now in #540 - https://github.com/ubclaunchpad/rocket2/issues/497 will track a longer-term fix

**Comment by ctong25** [comment]
Hi Robert,
If you closed it, I’m not supposed to be getting emails still right?
I just received one at 11:31AM.
Best regards,
Claudia Tong
tong.claudia.25@gmail.com
