### ISSUE TITLE
Rename '/rocket user deepdive' to '/rocket user view --inspect'

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#532]
seems a bit more ergonomic than a new command - it makes it easier for folks to do the same for their own profiles as well

deepdive was introduced in #523

**Comment by bobheadxi** [comment]
Assigned you for now @cheukyin699 but I could give it a try too if you want, just let me know!

**Comment by cheukyin699** [comment]
To make it easier for me I'll do `/rocket user view --inspect someid` so that it's compatible with the functions I wrote.

**Comment by bobheadxi** [comment]
How would that work with `/rocket user view --username`?

**Comment by cheukyin699** [comment]
No, because you can't do partially-optional options like that with argparse. That's why I opted for a new subcommand.

**Comment by cheukyin699** [comment]
Also, because `deepdive` works with both slack ids and github usernames, we'll have to look into a way to make it not clash with ui.

**Comment by bobheadxi** [comment]
Wouldnt it work alright with:

```
/rocket user view --username @bobheadxi --inspect
```

With https://github.com/ubclaunchpad/rocket2/issues/518 , we can reach parity with `deepdive` with:

```
/rocket user view --github bobheadxi --inspect
```

**Comment by cheukyin699** [comment]
Yup. That looks good. 

> No, because you can't do partially-optional options like that with argparse. That's why I opted for a new subcommand.

Okay prove me wrong why don't me https://stackoverflow.com/questions/4480075/argparse-optional-positional-arguments

Yes we can just not use the `--username` and `--github` options and just do it directly.

**Comment by bobheadxi** [comment]
I would leave the optional positional arguments for a different issue (we also need to decide if we want to just support Slack usernames in this manner, or if it should interpret Slack/GitHub usernames, etc.)

I'll put up a quick PR for #518 to unblock
