### ISSUE TITLE
command to export emails of subsets of users

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#539]
There are some miscellaneous bits of data that would be nice to be able to export, but doesn't seem to fit in anywhere with the other commands, so I'm proposing something like `/rocket export` that is admin-only, with currently:

* `/rocket export emails` for dumping emails, maybe supporting `--team $TEAM` and [possibly `--cohort $COHORT`](https://github.com/ubclaunchpad/rocket2/issues/538) in formats like comma-separated lists etc for easy copy-paste into gmail (@renehuang1999 )

**Comment by cheukyin699** [comment]
I... am not sure of the "easy copy-paste" thing, considering we have over 100 users. Probably can do with encasing everything in triple backticks.

**Comment by bobheadxi** [comment]
Maybe Rocket could upload a file attachment?

**Comment by cheukyin699** [comment]
> Maybe Rocket could upload a file attachment?

Can only upload via `files.upload` api, meaning that everyone would be able to see it if you do so in a public channel. Don't want to make too many mistakes.

**Comment by cheukyin699** [comment]
**OR** with significantly more work: route the file with GET request, only accessible with valid JWT and UUID

**Comment by bobheadxi** [comment]
> or maybe we can DM the person who is doing the commands.

I think this is the way to go for something like this 👍

**Comment by bobheadxi** [comment]
Use case for `export emails` from @DConnorFong :

> Next steps are to add your email address to the contact list here

https://ubclaunchpad.slack.com/archives/C01BX7V688K/p1602031051008700

**Comment by bobheadxi** [comment]
Narrowed the scope of this issue to just exporting emails
