### ISSUE TITLE
Audit broken links in documentation

### ISSUE THREAD

**Issue by tarikeshaq** [ubclaunchpad/rocket2#549]
## Summary

I noticed a couple of dead links in the documentation while going through [the local development guide](https://rocket2.readthedocs.io/en/latest/docs/LocalDevelopmentGuide.html)

## Reproduction steps

1. Go to https://rocket2.readthedocs.io/en/latest/docs/LocalDevelopmentGuide.html
2. On section 3.1, the link for "the Slack configuration docs" is broken
3. On section 5, the link for "GitHub key configuration docs " is also broken

## Expected behavior
Links should not be broken or should be taken off the docs if not relevant

Not sure when the docs were built but could be a good time to audit some of the info there as we get started with more people getting involved.

**Comment by bobheadxi** [comment]
I'm guessing this has something to do with the RST change, since iirc it worked when I landed the changes that added these links 🤔 

FYI all the links point to https://rocket2.readthedocs.io/en/latest/docs/Config.html
