### ISSUE TITLE
proposal: switch PR merge strategy to squashing

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#560]
## Summary

Switch the Rocket 2 project's pull request merge strategy to squashing.

## Requirements

The GitHub repository is updated to only accept squash merges when landing pull requests, and docs are updated to reflect that (they currently explicitly request that we do not squash, to preserve history).

## Context

With 1553 commits at time of writing, commits are essentially just noise at this point - lacking in context, overly numerous, and more often than not reflecting WIP states that do not reflect the actual state of changes in the repository (ie the goal is to preserve history, but it's not actually history)

Using a [commit-squashing strategy](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) explicitly ties each change to a PR and the associated discussions, which:

* improves `git blame` - you can actually see the full context of the change
* incentivize better commit bodies, since you are prompted to provide one at merge time
* less need to worry about beautiful commits when work is WIP, and more freedom to provide lots of commits
* encourages smaller-scoped PRs, since it becomes confusing to provide multiple changes in a single PR if they must end up squashed

The following Launch Pad projects also use squash:

* https://github.com/ubclaunchpad/inertia - switched to squash at ~1000 commits
* https://github.com/ubclaunchpad/docs
* https://github.com/ubclaunchpad/ubclaunchpad.com

**Comment by bobheadxi** [comment]
cc @cheukyin699 for thoughts

**Comment by cheukyin699** [comment]
I like it, though it will take us longer to get to the next goal of 2000 commits.

**Comment by bobheadxi** [comment]
Just send 2000 pull requests - easy cheese

**Comment by cheukyin699** [comment]
Something something hacktoberfest

**Comment by cheukyin699** [comment]
I'll set it up now?

**Comment by bobheadxi** [comment]
Yep! Just change it over and update the docs for it to close out this issue :) Thank you!
