### ISSUE TITLE
Ability to query logs by sending commands to Rocket

### ISSUE THREAD

**Issue by michaelenglo** [ubclaunchpad/rocket2#84]

**Comment by rwblickhan** [comment]
[Inertia](https://github.com/ubclaunchpad/inertia) has a similar command (`inertia $REMOTE logs`) that returns the most recent logs to the user. That may be a useful model.

**Comment by cheukyin699** [comment]
Closing in favour of using AWS Cloudwatch, and their ways of analytics. May reopen in the future if we get out of that onto a custom server or something.
